<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NuGetAudit>True</NuGetAudit>	  
  </PropertyGroup>


  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
	<ExcludeDevelopmentSettings>false</ExcludeDevelopmentSettings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="dotnet-tools.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="dotnet-tools.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
	 <PrivateAssets>all</PrivateAssets>
	 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
	 <PrivateAssets>all</PrivateAssets>
	 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Serilog.AspNetCore" />
	<PackageReference Include="Serilog.Settings.Configuration" />
	<PackageReference Include="Serilog.Sinks.Console" />
	<PackageReference Include="Serilog.Sinks.File" />
	<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
	<PackageReference Include="Swashbuckle.AspNetCore" />
	<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\App.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>


  <ItemGroup Condition="'$(ExcludeDevelopmentSettings)' == 'true'">
	<Content Update="appsettings.Development.json">
		<CopyToPublishDirectory>Never</CopyToPublishDirectory>
	</Content>

	<Content Update="appsettings.json">
		<TargetPath>appsettings.App.json</TargetPath>   
	</Content>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
	<DefineConstants>$(DefineConstants);PUBLISHED_APP</DefineConstants>
  </PropertyGroup>

</Project>
