// <auto-generated />
using System;
using Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AssetsCatalogContext))]
    partial class AssetsCatalogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Data.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GalleryId", "RelativePath" }, "Asset_GalleryId_IDX");

                    b.HasIndex(new[] { "GroupId", "GroupPosition" }, "Asset_GroupId_IDX");

                    b.HasIndex(new[] { "Hash" }, "Asset_Hash_IDX");

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("Data.Entities.AssetGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoverAssetIdx")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GalleryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhysicalRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GalleryId", "PhysicalRelativePath" }, "AssetGroups_GalleryId_IDX")
                        .IsUnique();

                    b.ToTable("AssetGroups");
                });

            modelBuilder.Entity("Data.Entities.AssetTag", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetId", "TagId");

                    b.HasIndex(new[] { "AssetId", "TagId" }, "ImageTags_ImageId_IDX")
                        .IsUnique();

                    b.HasIndex(new[] { "TagId", "AssetId" }, "ImageTags_TagId_IDX")
                        .IsUnique();

                    b.ToTable("AssetTags");
                });

            modelBuilder.Entity("Data.Entities.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CoverSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CoverSourceId");

                    b.ToTable("Galleries");
                });

            modelBuilder.Entity("Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CanonicalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CanonicalId" }, "Tags_CanonicalId_IDX");

                    b.HasIndex(new[] { "CategoryId" }, "Tags_CategoryId_IDX");

                    b.HasIndex(new[] { "Name" }, "Tags_Name_IDX")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Data.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TagCategories");
                });

            modelBuilder.Entity("Data.Entities.Asset", b =>
                {
                    b.HasOne("Data.Entities.Gallery", "Gallery")
                        .WithMany("Assets")
                        .HasForeignKey("GalleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.AssetGroup", "Group")
                        .WithMany("Assets")
                        .HasForeignKey("GroupId");

                    b.Navigation("Gallery");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Data.Entities.AssetGroup", b =>
                {
                    b.HasOne("Data.Entities.Gallery", "Gallery")
                        .WithMany("AssetGroups")
                        .HasForeignKey("GalleryId")
                        .IsRequired();

                    b.Navigation("Gallery");
                });

            modelBuilder.Entity("Data.Entities.AssetTag", b =>
                {
                    b.HasOne("Data.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Data.Entities.Gallery", b =>
                {
                    b.HasOne("Data.Entities.Asset", "CoverSource")
                        .WithMany("Galleries")
                        .HasForeignKey("CoverSourceId");

                    b.Navigation("CoverSource");
                });

            modelBuilder.Entity("Data.Entities.Tag", b =>
                {
                    b.HasOne("Data.Entities.Tag", "Canonical")
                        .WithMany("InverseCanonical")
                        .HasForeignKey("CanonicalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Data.Entities.TagCategory", "Category")
                        .WithMany("Tags")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.Navigation("Canonical");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Data.Entities.Asset", b =>
                {
                    b.Navigation("Galleries");
                });

            modelBuilder.Entity("Data.Entities.AssetGroup", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Data.Entities.Gallery", b =>
                {
                    b.Navigation("AssetGroups");

                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Data.Entities.Tag", b =>
                {
                    b.Navigation("InverseCanonical");
                });

            modelBuilder.Entity("Data.Entities.TagCategory", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
